### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'gradInput'

### ISSUE THREAD

**Issue by ph-preux** [clcarwin/convert_torch_to_pytorch#21]
running convert_torch.py, I have this issue:
$ python ~/usr/convert_torch_to_pytorch/convert_torch.py -m file.t7
Traceback (most recent call last):
  File "/home/ppreux/usr/convert_torch_to_pytorch/convert_torch.py", line 314, in <module>
    torch_to_pytorch(args.model,args.output)
  File "/home/ppreux/usr/convert_torch_to_pytorch/convert_torch.py", line 261, in torch_to_pytorch
    model.gradInput = None
AttributeError: 'NoneType' object has no attribute 'gradInput'

Thanks for any help

**Comment by clcarwin** [comment]
You can debug the code to find where ```model``` is changed to None.
